### ISSUE TITLE
Dark mode colors seem a little bit off and friends tab is smaller

### ISSUE THREAD

**Issue by jasonandreou** [nimsandu/spicetify-bloom#146]
The theme colors aren't really dark like in the repo image and the friends tab is squished.

![image](https://user-images.githubusercontent.com/106876045/211192177-ea29d7ff-1c50-45d4-9949-c5387c5f444c.png)

**Comment by nimsandu** [comment]
Repo image is a screenshot of my personal Spotify desktop and its not altered in any way.

So your image and ours is identical 

But your feeling is real and thanks for reaching out 

Thanks to you i came up with an idea to implement a brand new scheme called midnight so it will be pure dark theme.

But remember it will never be the default scheme as we choose current colors to be matched with windows 11 default bloom wallpaper. And that's because our theme is called bloom.
This color choice makes an illusion of a windows 11 application with mica backdrop.

But don't worry we will implement midnight asap to delver something that you can personally enjoy @jasonandreou 

Thanks for reaching out

**Comment by nimsandu** [comment]
@jasonandreou thanks to #158 by @SunsetTechuila 
now you can experience bloom in a way that you wanted. check out the scheme Dark mono
run `spicetify config color_scheme darkmono` to bloom the way you want!

**Comment by jasonandreou** [comment]
That’s great! Thank you.

**Comment by nimsandu** [comment]
@jasonandreou Enjoy bloom
