### ISSUE TITLE
Slight issues with random floating icons

### ISSUE THREAD

**Issue by Jazza-231** [nimsandu/spicetify-bloom#149]
I overall love this theme, it's really great, but there is an issue which will mean I'll use another theme for now...screenshots attached, there are essentially floating play, pause and volume icons, probably a conflict with extensions/snippets I have?
![image](https://user-images.githubusercontent.com/81956724/212543006-8738b099-cfe6-4ea9-ac70-0aaec59db3ee.png)
<img width="78" alt="image" src="https://user-images.githubusercontent.com/81956724/212543014-f51c5814-2d46-4d1c-8b7e-0bb5ef98e54e.png">

**Comment by nimsandu** [comment]
@Jazza-231 Thanks for reaching out 

Those icons are ment to be a feature. When you play one of your playlist then that pause button appears on that particular playlist. If you click on it song will pause. But due to an unsolved issue when you play liked songs it shows an volume icon instead but it works similarly. 

Could I know how this icons interrupt your experience. Because we can remove this feature easily. 
Please inform us. We love to hear your opinion

Thanks

**Comment by Jazza-231** [comment]
Ah i wasn't aware it was a feature, if the volume icon could be fixed, and the icons being properly aligned then I would have no issue, but the fact that neither of the icons are actually aligned to the liked songs, especially the play button in the second screenshot, if that could be fixed then all would be good.
Thanks for the quick reply btw!

**Comment by TukangM** [comment]
ahh. thanks to report. i just wanted report this bug. before report bug. i looking issues list and found this :D. nice

**Comment by SunsetTechuila** [comment]
Duplicate of #130
