### ISSUE TITLE
Problem with text colors

### ISSUE THREAD

**Issue by SakethKanchi** [nimsandu/spicetify-bloom#154]
Spotify for Windows 1.2.5.954.gf42f9f0a
Spicetify v2.16.1

It's been an issue on the previous versions as well. For any dark theme "dracula", "comfy" and "dark". Only the light theme text works properly.

![image](https://user-images.githubusercontent.com/70198692/218808135-8ea7a7ba-eec2-44e6-830c-62c14fee6898.png)

**Comment by nimsandu** [comment]
@SakethKanchi 
this issue was fixed with #156 
now it looks like this.
![image](https://user-images.githubusercontent.com/57834844/218952493-c2430c06-06d2-43a5-82c7-34e4a0e2165b.png)

thanks for reaching out.
close this issue by yourself after installing latest version using installation script.
don't forget to conform the fix and suggest any enhancements. 
enjoy bloom.
