### ISSUE TITLE
The Pop-up notification which confirms the adding of a new song to a playlist is displayed under the Now playing bar

### ISSUE THREAD

**Issue by Expertdboomer** [nimsandu/spicetify-bloom#333]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.33.10.9.g8ddb5918
- Installed from: Spotify Site
- Spicetify version: v2.24.2
- Color scheme: darkmono
- Extensions: Beautiful Lyrics, Adblock, Spicetify-Hide-Podcasts, Display Full Album date, Play enhanced Songs, Volume Percentage, Play on Youtube, spoqify-radios, No Tracking Links, WebNowPlaying-Redux
- Custom apps: none
- Bloom installation method: Spicetify Marketplace
```

### Description

Steps to reproduce 
* Have Bloom installed 
* Drag and drop a song onto a playlist icon on the sidebar
* The popup will display under the now playing row 
  ( It can be observed by seeing the colour change from the default theme colour to blue under the blurred now playing row)

### Screenshots

![Smcreenshot 2024-03-21 232143](https://github.com/nimsandu/spicetify-bloom/assets/162906403/b7d3f01c-3343-4aee-a6ee-bf8a67edcf33)
![Screenshot 2024-03-21 233457](https://github.com/nimsandu/spicetify-bloom/assets/162906403/c9822337-c396-41be-927b-18b18cd5b69f)

**Comment by stel-bl** [comment]
Spotify, oh, Spotify... They must have changed the code for it again...

And we, as the main developers of Bloom, can't work on it yet because of the real life situations we have over here.

There was @SunsetTechuila carrying out the heavy lifting for the last time, but he had to leave for his life as well.

As for me, I'm just a script monkey. I'm here to work on the installation scripts and organizing things around as a power user. I know jack shit about Spicetify theme development.

@nimsandu **might** be able to look into this, but I'm pretty sure it would take him a while until he can de-rust after all the rusting due to his own life...

I'll see if I can find anyone who can help fix all these issues in the first place, because Bloom is no longer maintained properly for now despite still being recommended and used actively all over the world.

**Comment by nimsandu** [comment]
@stel-bl ill look into that!! thanks guys you are lifesavers!

**Comment by stel-bl** [comment]
> @stel-bl ill look into that!! thanks guys you are lifesavers!

Good luck, @nimsandu! Hope for the best!

**Comment by nimsandu** [comment]
@Expertdboomer fixed!!!

![image](https://github.com/nimsandu/spicetify-bloom/assets/57834844/8447b90f-5fd4-4cd1-b393-3244d23829ac)

**Comment by nimsandu** [comment]
@Expertdboomer if it still happens, please reopen the issue mate
