### ISSUE TITLE
Theme uses apple store icon for marketplace

### ISSUE THREAD

**Issue by Eatham532** [nimsandu/spicetify-bloom#336]
### Provide a description of the new feature

Ok, so this is a Microsoft Fluent design system inspired theme... And yet you use the Apple store icon for the marketplace. Also, it just looks bad as the icon doesnt represent what the actual tab is for. Some better options could be a basket icon or some other icon to represent a market place and not the apple app store.

**Comment by stel-bl** [comment]
Excuse my rudeness but this is something you definitely deserve IMO.

Why not open a PR for a "better" icon or link one here instead of just complaining about it? It's been that way for years and there was not a single person to complain. Also, the Spicetify Marketplace is the store for, well, Spicetify add-ons and themes. Isn't it normal for there to be a store icon instead of just a basket or something?

Again, contributions are welcome. Even the icons are pretty easy to find if you know how things are commonly organized throughout the websites (if you still can't figure out where, it's right in `assets/fluentui-system-icons/` as vector drawable, named `ic_fluent_app_store_24_*.svg`). Just fork this repo, replace the icon in an editor like InkScape, change the references in code if you change the filename and you're done.

Oh, even better yet, why don't we ask the actual one who committed the icon, @TheChilledBuffalo, about this? I'm sure you can figure out that this person was the one who committed this if you just check the Git history of the file.

Sigh...enough ranting. If you really want an enhancement about this, **go find some actual resources and/or references we can look at**.

Thank you.

**Comment by TheChilledBuffalo** [comment]
I'm sorry, @stel-bl , just some clarification, but how am I involved here? I didn't submit the App Store icons lol. My commits were the statistics, better local files and better library icons. And those icons were taken directly from microsoft's fluent icon library here on github: https://github.com/microsoft/fluentui-system-icons

**Comment by TheChilledBuffalo** [comment]
And also, @Eatham532 , the App Store icons were also taken from *Microsoft*'s own library of fluent icons: https://github.com/microsoft/fluentui-system-icons/blob/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/App%20Store/SVG/ic_fluent_app_store_24_filled.svg?plain=1

They have absolutely no issues providing assets of something of their "competitor" and it does seem like the an appropriate choice for Marketplace. So uhm... what's your deal?

**Comment by stel-bl** [comment]
> I'm sorry, @stel-bl , just some clarification, but how am I involved here? I didn't submit the App Store icons lol. My commits were the statistics, better local files and better library icons. And those icons were taken directly from microsoft's fluent icon library here on github: https://github.com/microsoft/fluentui-system-icons

Pfft sorry @TheChilledBuffalo, I read the log incorrectly. Now checking it again and it seems to have been committed by someone without a GitHub account linked to the committer credentials (`lemonbigbig <me@lemon66.tech>` - https://github.com/nimsandu/spicetify-bloom/commit/b97ea1ceba97f283d8df2582e707e0e191558a23). Guess I let my anger take over to the point I oversaw that. :sweat:

**Comment by Eatham532** [comment]
Lol ok... 
I just never liked it because I was used to the normal marketplace icon. And seeing an Appstore icon on windows gave me weird vibes like I was on a mobile device.

Maybe instead of the AppStore icon use the Apps icon: https://github.com/microsoft/fluentui-system-icons/tree/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/Apps

Or the apps add in one: https://github.com/microsoft/fluentui-system-icons/tree/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/Apps%20Add%20In

The shopping bag could also work: https://github.com/microsoft/fluentui-system-icons/tree/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/Shopping%20Bag

Sorry for nitpicking. This theme is one of my favorites so I was just trying to help with the few things I don't really like.

**Comment by stel-bl** [comment]
> Lol ok... I just never liked it because I was used to the normal marketplace icon. And seeing an Appstore icon on windows gave me weird vibes like I was on a mobile device.

Fair enough, it's alright.
> Maybe instead of the AppStore icon use the Apps icon: https://github.com/microsoft/fluentui-system-icons/tree/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/Apps
> 
> Or the apps add in one: https://github.com/microsoft/fluentui-system-icons/tree/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/Apps%20Add%20In

This one looks far better IMHO. Good find!

> The shopping bag could also work: https://github.com/microsoft/fluentui-system-icons/tree/d32cd7114b430cbdcce2c354e5fa010566a2582b/assets/Shopping%20Bag

Nah this looks way too out of place TBH. But yeah, the apps add-in one is a good find, I think we should give that one a try.

> Sorry for nitpicking. This theme is one of my favorites so I was just trying to help with the few things I think could be improved. If you don't like the ideas there then that's ok. Don't feel like you have to follow through with my suggestions just because I have a different opinion to you.

Again, it's alright. I was mad because of the overhead I've been having trying to deal with the users that don't give a reference for the bug/suggestion. You're good, I'm sorry for my reaction.

**Comment by Eatham532** [comment]
No problem

> I was mad because of the overhead I've been having trying to deal with the users that don't give a reference for the bug/suggestion.

Lol I understand. Those people can be so frustrating.
