### ISSUE TITLE
Remote install broken

### ISSUE THREAD

**Issue by cmdshft** [nimsandu/spicetify-bloom#353]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: Spotify site
- Spicetify version: 2.36.11
- Color scheme: dark
- Bloom installation method: PowerShell script
```

### Description

1: Run Powershell script
2: Run remote option
2: Run Spotify

Some of the control icons are out of alignment or even just missing (such as shuffle). The control panel seems to also be too low in the window than what is shown in the description screenshots.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/8571823/5a9148ce-bd7d-45d4-a997-1cb752e8f2b2)

**Comment by sanoojes** [comment]
It is fixed in this pull hope @nimsandu merges it

https://github.com/nimsandu/spicetify-bloom/pull/352

**Comment by sanoojes** [comment]
also checkout [better-bloom](https://github.com/sanoojes/better-bloom) theme. i rewrote all the css and js

**Comment by nimsandu** [comment]
> It is fixed in this pull hope @nimsandu merges it
> 
> #352

@sanoojes hey!! sorry for delays! well thanks to you, its fixed!
@cmdshft ill close the issue, please reopen if anything goes wrong again!

**Comment by sanoojes** [comment]
no probs can i re write the theme i rewrote the whole code and made a new theme with advancements if you like it we can merge the project @nimsandu

**Comment by sanoojes** [comment]
it was previously named better-bloom now its called Lucid => https://github.com/sanoojes/Spicetify-Lucid
also am also looking forward to make a discord bloom theme

**Comment by nimsandu** [comment]
@sanoojes , Hey, I've already seen it (I even starred the repo), and I absolutely love it! It's a completely new experience and it's really nice. I remember @SunsetTechuila created a mica-simulated version for Bloom that felt just like this, and I personally adore it!

So, Sanoojes, I truly believe Lucid deserves to be an independent theme. If you want, I can let you integrate it with Bloom, but personally, I'd love to see it stand out because you've worked hard and completely redefined it. I created this using the Fluent theme by William Ha, and look how far we've come! I think you can embark on a journey like that. I will personally assist with anything!

We don't do this for ourselves; we never have. It's all about making people's lives a little bit better. It needs evolutions! I see you can conquer Spicetify with this wonderful theme.

so what do you think?

**Comment by sanoojes** [comment]
@nimsandu  Thank you so much for the incredibly kind words and support! 

i would like to integrate the theme with bloom with its own spice ! 

| sorry for been bad at communicating in english |

**Comment by nimsandu** [comment]
okayy! as you will! @sanoojes ! 
so here is the plan;
we introduce this as a separate scheme for bloom just like the violet coffee schemes etc.
in order to do that we can include lucid in a sub files in the repo and edit the installation scripts asking the users to choose what scheme they want to install! just like we already ask users to choose Remote and Local during installation! this will let end user to choose with ease while giving lucid the proper place it deserves! this kind of approach will help you to integrate the upcoming discord theme with ease too! also allowing our contributors to do what you do easily!

**Comment by nimsandu** [comment]
@sanoojes also, open a discussion, that will help us discuss better! (also no need of good English when the code speaks ;)

**Comment by sanoojes** [comment]
yes sure i will do that now am going to rewrite some css and fix the theme issues

**Comment by sanoojes** [comment]
> okayy! as you will! @sanoojes ! so here is the plan; we introduce this as a separate scheme for bloom just like the violet coffee schemes etc. in order to do that we can include lucid in a sub files in the repo and edit the installation scripts asking the users to choose what scheme they want to install! just like we already ask users to choose Remote and Local during installation! this will let end user to choose with ease while giving lucid the proper place it deserves! this kind of approach will help you to integrate the upcoming discord theme with ease too! also allowing our contributors to do what you do easily!

yes sure we can do like it ! do you have discord or any other app for development chat ? @nimsandu

**Comment by nimsandu** [comment]
@sanoojes im on discord, well somehow your link isnt working!
heres mine : [discord](https://discord.gg/g4qzpj37)
